apiVersion: skaffold/v3alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: meetkumar/meet-client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.js"
          dest: .

  - image: meetkumar/meet-comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "*.js"
          dest: .

  - image: meetkumar/meet-posts-latest
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "*.js"
          dest: .

  - image: meetkumar/meet-query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "*.js"
          dest: .

  - image: meetkumar/meet-eventbus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "*.js"
          dest: .

  - image: meetkumar/meet-moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "*.js"
          dest: .
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}